/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gg;

import com.mongodb.BasicDBObject;
import com.mongodb.MongoClient;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.bson.Document;

/**
 *
 * @author Student.Admin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
//        Connect();
//        this.setLocationRelativeTo(null);
    }
    
//    MongoCollection<org.bson.Document> collection;
//    
//    public void Connect() {
//        MongoClient mongoToqs = new MongoClient("localhost", 27017);
//        MongoDatabase dbconnection = mongoToqs.getDatabase("JavaMongodb");
//        collection = dbconnection.getCollection("users");
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg (2).jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 110, 80));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 90, 60));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        email.setFont(new java.awt.Font("Century Gothic", 1, 18));
        email.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 270, 50));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log in");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 150, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 120));

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("\"I'm not a geek....");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("I'm a gamer\"");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 310, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Click Here to Register");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 180, 40));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 270, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg (2).jpg"))); // NOI18N
        jLabel11.setText("jLabel10");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new Signup().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
//        
        String user_name = email.getText();
        
        String passwrd = String.valueOf(pass.getPassword());
        if (user_name.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Email:");
        } else if (passwrd.equals("")) {
            JOptionPane.showMessageDialog(null, "Add a Password:");
        } else {

            MongoClient mongoClient = new MongoClient("localhost", 27017);
            MongoDatabase db = mongoClient.getDatabase("JavaMongodb");
            MongoCollection collection = db.getCollection("users");

            FindIterable<Document> user; // Change to get the object of FindIterable<Document>

            user = collection.find(new Document("Email", user_name));// give Document as the find() argument
            if (user != null) {
                System.out.println("User not in database");

            
            }
            String hashedAndSalted = user.first().get("Password").toString();// get user.first()


            if (!hashedAndSalted.equals(passwrd)) {
                JOptionPane.showMessageDialog(null, "Incorrect password");
                System.out.println();
            }
            else{
                dashboard toqs = new dashboard();
                toqs.setVisible(true);
                toqs.pack();
                toqs.setLocationRelativeTo(null);
                toqs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
            }


        }
//             String Email = email.getText();
//             String Password = pass.getText();
//             BasicDBObject identify = new BasicDBObject();
//             identify.put("email", Email);
//             identify.put("password", Password);
//             
//             MongoCursor<Document> query = collection.find(identify).iterator();
//             
//             if(Email.equals("")&&(Password.equals(""))){
//                 JOptionPane.showMessageDialog(this,"All fields is required");
//             }else if(!Email.equals("")&&(Password.equals(""))){
//                 JOptionPane.showMessageDialog(this,"Password field is required");
//             }
//             else if(Email.equals("")&&(!Password.equals(""))){
//                 JOptionPane.showMessageDialog(this,"Email field is required");
//             }
//             else {
//                 if (query.hasNext()){
//                 new dashboard().setVisible(true);
//                 setVisible(false);
//                 }
//             }


//        if (email.getText().trim().isEmpty() && pass.getText().trim().isEmpty()) {
//            email.setText("Email is Empty");
//            pass.setText("Password is Empty");
//        } else if (email.getText().trim().isEmpty()) {
//            email.setText("Email is Empty");
//        } else if (pass.getText().trim().isEmpty()) {
//            pass.setText("Password is Empty");
//        } else {
//        }  
//
//                JFrame f = new JFrame();
//        try {
//                MongoClient mongoClient = new MongoClient("localhost", 27017);
//                
//                
//
//                MongoDatabase db = mongoClient.getDatabase("JavaMongodb");
//
//                MongoCollection<Document> table = db.getCollection("users");
////                table.find(eq("student_id", 10000)).first();
//
//                // find one document with new Document
//                Document result = table.find(new Document("Email", this.email.getText())).first();
////                 System.out.println(result.isEmpty());
//                if (result.get("Email").equals(this.email.getText()) && result.get("password").equals(this.pass.getText())) {
//                    JOptionPane.showMessageDialog(f, "Successfully login!", "Alert", JOptionPane.WARNING_MESSAGE);
//                     dashboard jf = new dashboard();
//                     jf.setVisible(true);
//                       setVisible(false);
////                    new WelcomeJFrame(this.username.getText(), this.password.getText()).setVisible(true);
//                } else {
//                    JOptionPane.showMessageDialog(f, "Incorrect credentials!", "Alert", JOptionPane.WARNING_MESSAGE);
//                    this.pass.setText("");
//                }
//
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(f, "Incorrect credentials!", "Alert", JOptionPane.WARNING_MESSAGE);
//                this.pass.setText("");
//            }

    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
}
